Version 4
SymbolType BLOCK
RECTANGLE Normal 32 32 -64 -64
SYMATTR Prefix X
SYMATTR Value ZHT431
PIN 0 -64 TOP 8
PINATTR PinName VZ
PINATTR SpiceOrder 1
PIN -64 -16 LEFT 8
PINATTR PinName VREF
PINATTR SpiceOrder 2
PIN 0 32 BOTTOM 8
PINATTR PinName GND
PINATTR SpiceOrder 3
